plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.googletv'
    compileSdk 36

    defaultConfig {
        applicationId 'com.example.googletv'
        minSdk 21
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['.']
        }
    }
}
